# Generated by Django 5.1.3 on 2024-12-04 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_revision_hora_hecho'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='hora_revision',
            field=models.DateTimeField(null=True),
        ),
    ]
