# Generated by Django 5.1.3 on 2024-12-05 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_registro_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='hora',
            field=models.DateTimeField(null=True),
        ),
    ]
